"""Initial migration

Revision ID: a4b1c4717e6d
Revises: 
Create Date: 2025-01-20 21:09:13.013405

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a4b1c4717e6d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
